# Generated by Django 3.0.3 on 2020-02-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200203_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entrees', 'entrees'), ('drinks', 'drinks'), ('treats', 'treats'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
