# Generated by Django 3.0.3 on 2020-02-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20200204_1741'),
        ('products', '0002_auto_20181101_2355'),
    ]

    operations = [
    ]
